"""Hardcoded sceneview response for 3DSLICER subscriber (cast-get)."""

SCENEVIEW_3DSLICER_RESPONSE = {
    "subscriber": "3DSLICER",
    "dataType": "SCENEVIEW",
    "exists": True,
    "connected": False,
    "topic": None,
    "endpoint": None,
    "response": {
        "source": "sceneview",
        "file": "2026-01-27-Scene.mrml",
        "viewports": [
            {
                "type": "View",
                "id": "vtkMRMLViewNode1",
                "name": "View1",
                "layoutLabel": "1",
                "layoutName": "1",
                "fieldOfView": "200",
                "camera": {
                    "position": "-2124.05 1319.11 -596.768",
                    "focalPoint": "-246.198 -59.8098 -413.602",
                    "viewUp": "-0.0217135 0.102532 0.994493",
                    "viewAngle": "30",
                    "parallelProjection": "false",
                    "parallelScale": "1",
                },
            },
            {
                "type": "Slice",
                "id": "vtkMRMLSliceNodeRed",
                "name": "Red",
                "layoutLabel": "R",
                "layoutName": "Red",
                "orientation": "Axial",
                "fieldOfView": "531.095 500 5",
                "dimensions": "427 402 1",
                "sliceToRAS": "-1 0 0 -2.84217e-14 0 1 0 178 0 0 1 -734.5 0 0 0 1",
            },
            {
                "type": "Slice",
                "id": "vtkMRMLSliceNodeGreen",
                "name": "Green",
                "layoutLabel": "G",
                "layoutName": "Green",
                "orientation": "Coronal",
                "fieldOfView": "924.104 870 0.976562",
                "dimensions": "427 402 1",
                "sliceToRAS": "-1 0 0 -2.84217e-14 0 0 1 226.34 0 1 0 -447 0 0 0 1",
            },
            {
                "type": "Slice",
                "id": "vtkMRMLSliceNodeYellow",
                "name": "Yellow",
                "layoutLabel": "Y",
                "layoutName": "Yellow",
                "orientation": "Sagittal",
                "fieldOfView": "924.104 870 0.976562",
                "dimensions": "427 402 1",
                "sliceToRAS": "0 0 -1 104.004 -1 0 0 178 0 1 0 -447 0 0 0 1",
            },
        ],
    },
}
